### PR TITLE
Add some more valid cite commands

### PR DESCRIPTION
**Pull request by katrielalex**
This will probably allow some invalid ones, but I'm not sure that's a problem.

(I haven't tested this change.)

### CODE REVIEW

**Comment by PJK** [comment]
LGTM but the regex is getting a bit unwieldy, I would prefer to add at least a few basic test cases first to sanity-check it (no, there are no tests :/) and then get back to this. ETA Saturday.

**Comment by katrielalex** [comment]
👍 good plan

Would it make sense to replace the cite regex with e.g. `\{DBLP.*?\}` i.e. just match anything that vaguely looks like it might be a DBLP key? If some of the matches are invalid the script could just handle that case, and then you don't have to play whack-a-mole with new and exciting cite commands.

**Comment by BioCommSec** [comment]
@katriel i have a project im working on and could use your help.  Whats your e mail add?

**Comment by PJK** [comment]
Here we go, sorry for the delay

**Pull request merged**
