### PR TITLE
Added support for natbib citation commands.

### PR DESCRIPTION
**Pull request by edlanglois**
The additional supported commands are:
  - cite(al)?[pt]\*?
  - citeauthor\*?
  - citeyear(par)?

Reference:
http://merkel.texture.rocks/Latex/natbib.php

### CODE REVIEW

**Comment by katrielalex** [comment]
It would be nice to have \textcite and \autocite as well :)

**Comment by PJK** [comment]
Sorry for keeping this open for so long, I haven't noticed the PR. Shame on me. Thank you for contributing!

**Comment by PJK** [comment]
@katrielalex feel free to open a PR to add those, I am personally not using them

**Comment by katrielalex** [comment]
#3 ;)

PS thank you for making this, it's great!

**Pull request merged**
